apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-api-deployment
  namespace: distribuidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todos-api
  template:
    metadata:
      labels:
        app: todos-api
    spec:
      containers:
        - name: todos-api-container
          image: sgutierrez11/todos-api:0.0.1
          ports:
            - containerPort: 8082
          env:
            - name: TODO_API_PORT
              value: "8082"
            - name: JWT_SECRET
              value: "PRFT"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
