apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
      - name: log-message-processor
        image: sebastiannavia/app-log-message:0.1.0
        ports:
        - containerPort: 6029
        env: 
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: log_channel

---
apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
spec:
  selector:
    app: log-message-processor
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6029
