apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor
  namespace: microservice-app-example
  labels:
    app: log-message-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor
          image: danieljaraba/log-message-processor:0.0.4
          ports:
            - containerPort: 3000
