apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: microservice-app-example
spec:
  selector:
    app: log-message-processor
  ports:
    - name: log-message-port
      port: 3000
      targetPort: 3000
  type: ClusterIP