apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: microservice-app-example
spec:
  selector:
    app: auth-api
  ports:
    - name: auth-api-port
      port: 8000
      targetPort: 8000
  type: ClusterIP