apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservice-app-example
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: danieljaraba/microservice-front:latest
          ports:
            - containerPort: 8080
