apiVersion: v1
kind: Service
metadata:
  name: todos-api
  namespace: microservice-app-example
spec:
  selector:
    app: todos-api
  ports:
    - name: todos-api-port
      port: 8082
      targetPort: 8082
  type: ClusterIP