apiVersion: v1
kind: Service
metadata:
  name: auth-api
  namespace: distribuidos
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: http
