apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api-deployment
  namespace: distribuidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api-container
          image: sgutierrez11/users-api:0.0.1
          ports:
            - containerPort: 8083
          env:
            - name: JWT_SECRET
              value: PRFT
            - name: SERVER_PORT
              value: "8083"
