apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-channel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-channel
  template:
    metadata:
      labels:
        app: log-channel
    spec:
      containers:
      - name: log-channel
        image: ventana1901/log-channel:v1
        ports:
        - containerPort: 6029
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_CHANNEL
          value: "log-channel"