apiVersion: v1
kind: Service
metadata:
  name: redis-stack-server
  namespace: microservice-app-example
spec:
  selector:
    app: redis-stack-server
  ports:
    - name: redis-port
      port: 6379
      targetPort: 6379
  type: ClusterIP