apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-message-processor-deployment
  namespace: distribuidos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-message-processor
  template:
    metadata:
      labels:
        app: log-message-processor
    spec:
      containers:
        - name: log-message-processor-container
          image: sgutierrez11/log-message-processor:0.0.1
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_CHANNEL
              value: "log_channel"
