apiVersion: v1
kind: Service
metadata:
  name: log-message-processor
  namespace: distribuidos
spec:
  selector:
    app: log-message-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
