apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: distribuidos
  labels:
    app: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      type: redis
  template:
    metadata:
      labels:
        app: redis
        type: redis
    spec:
      containers:
        - name: redis
          image: redis/redis-stack-server:latest
          ports:
            - containerPort: 6379
