apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: microservice-app-example
  labels:
    app: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      containers:
        - name: users-api
          image: arturodiaz02/microservice-app-example-users
          ports:
            - containerPort: 8083
          env:
            - name: SERVER_PORT
              value: "8083"
            - name: JWT_SECRET
              value: PRFT
