apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: microservice-app-example
spec:
  selector:
    app: users-api
  ports:
    - name: users-api-port
      port: 8083
      targetPort: 8083
  type: ClusterIP